#target aftereffects
// Generated by MADSearcher, script layout v2. Pixel sequences stay read-only.
(function () {
    var data = __PAYLOAD__;
    var scriptFolder = new File($.fileName).parent;
    function asset(path) {
        return new File(/^(?:[A-Za-z]:|\/)/.test(path) ? path : scriptFolder.fsName + "/" + path);
    }
    function checkSequence(path) {
        for (var i = 0; i < data.count; i++) {
            var number = ("000000" + i).slice(-6);
            if (!asset(path.replace(/000000\.png$/, number + ".png")).exists) {
                throw new Error("Missing PNG frame " + number + ". Keep the complete cutout folder together.");
            }
        }
    }
    try {
        if (data.mode !== "paths") checkSequence(data.rgba);
        if (data.mode !== "rgba") checkSequence(data.source);
    } catch (missing) { alert("MADSearcher: " + missing.toString()); return; }

    app.beginUndoGroup("MADSearcher cutout - " + data.mode);
    try {
        if (!app.project) app.newProject();
        var target = app.project.activeItem;
        var duration = data.count / data.fps;
        var folder = app.project.items.addFolder("MADSearcher " + data.name);
        function makeComp(name) {
            var comp = app.project.items.addComp(name, data.width, data.height, 1, duration, data.fps);
            comp.parentFolder = folder;
            comp.motionBlur = false;
            comp.frameBlending = false;
            return comp;
        }
        function layerDefaults(layer, name) {
            layer.name = name;
            layer.startTime = 0;
            layer.inPoint = 0;
            layer.outPoint = duration;
            layer.motionBlur = false;
            layer.frameBlendingType = FrameBlendingType.NO_FRAME_BLEND;
            layer.quality = LayerQuality.BEST;
            return layer;
        }
        function importSequence(path, name, alpha) {
            var options = new ImportOptions(asset(path));
            options.sequence = data.count > 1;
            options.forceAlphabetical = true;
            var footage = app.project.importFile(options);
            footage.name = name;
            footage.parentFolder = folder;
            if (footage.width !== data.width || footage.height !== data.height) {
                throw new Error("PNG dimensions changed after export.");
            }
            if (!footage.mainSource.isStill) {
                footage.mainSource.conformFrameRate = data.fps;
                if (footage.duration + 0.001 < duration) throw new Error("PNG sequence is shorter than expected.");
            }
            if (alpha) {
                if (!footage.mainSource.hasAlpha) throw new Error("RGBA sequence has no alpha channel.");
                footage.mainSource.alphaMode = AlphaMode.STRAIGHT;
                footage.mainSource.invertAlpha = false;
            } else if (footage.mainSource.hasAlpha) {
                footage.mainSource.alphaMode = AlphaMode.IGNORE;
            }
            return footage;
        }
        function polygon(points) {
            var shape = new Shape();
            shape.vertices = points;
            shape.closed = true;
            var tangents = [];
            for (var p = 0; p < points.length; p++) tangents.push([0,0]);
            shape.inTangents = tangents;
            shape.outTangents = tangents;
            return shape;
        }
        function repairLayer(comp, name, erase, original) {
            // Restore uses the synchronized, opaque original so masks preview in color.
            var sourceLayer = erase ? comp.layers.addSolid([1,1,1], name, data.width, data.height, 1, duration) : comp.layers.add(original);
            var layer = layerDefaults(sourceLayer, name);
            if (erase) layer.source.parentFolder = original.parentFolder;
            // Adobe's scripting enum intentionally spells SILHOUETE with one T.
            layer.blendingMode = erase ? BlendingMode.SILHOUETE_ALPHA : BlendingMode.NORMAL;
            layer.label = erase ? 1 : 9;
            var mask = layer.property("ADBE Mask Parade").addProperty("ADBE Mask Atom");
            mask.name = "空占位：保留此蒙版，另画添加蒙版";
            mask.maskMode = MaskMode.ADD;
            mask.inverted = false;
            mask.rotoBezier = false;
            mask.property("ADBE Mask Feather").setValue([0,0]);
            mask.property("ADBE Mask Offset").setValue(0);
            mask.property("ADBE Mask Opacity").setValue(100);
            mask.property("ADBE Mask Shape").setValue(polygon([[-4,-4],[-3,-4],[-3,-3]]));
            layer.comment = "选中此层，用钢笔另画闭合添加蒙版。可为新蒙版路径加关键帧或调整羽化；缩短图层范围可只修几帧。";
            return layer;
        }
        function addEffect(layer, matchName, name) {
            var effects = layer.property("ADBE Effect Parade");
            if (!effects.canAddProperty(matchName)) throw new Error("AE缺少必要效果：" + matchName);
            var effect = effects.addProperty(matchName);
            effect.name = name;
            return effect;
        }
        function oneD(effect, matchName) {
            var parameter = effect.property(matchName);
            if (!parameter || parameter.propertyType !== PropertyType.PROPERTY || parameter.propertyValueType !== PropertyValueType.OneD) {
                throw new Error("AE效果参数不兼容：" + matchName);
            }
            return parameter;
        }
        function signedAmount(effect) {
            // Simple Choker has one signed scalar (Choke Matte) plus its View menu.
            // Find by the parameter contract, not a localized display name or menu index.
            var amount = null;
            for (var i = 1; i <= effect.numProperties; i++) {
                var parameter = effect.property(i);
                if (parameter.propertyType === PropertyType.PROPERTY && parameter.propertyValueType === PropertyValueType.OneD &&
                        parameter.hasMin && parameter.hasMax && parameter.minValue < 0 && parameter.maxValue > 0) {
                    if (amount) throw new Error("AE边缘收缩效果含有多个有符号参数，无法安全设置。");
                    amount = parameter;
                }
            }
            if (!amount) throw new Error("AE边缘收缩效果参数不兼容。");
            return amount;
        }
        function edgeControl(comp, matteLayer, assets) {
            var control = layerDefaults(comp.layers.addNull(duration), "01 整体边缘（效果控件）");
            control.source.parentFolder = assets;
            control.label = 10;
            control.comment = "在效果控件调整整圈边缘。柔化建议从1–2像素开始；收缩正值向内、负值向外。两个值归零恢复原边缘。双击下方局部修补层可补回/去除，修补后在本合成查看整体边缘。";
            var softenName = "边缘柔化（像素）";
            var chokeName = "边缘收缩（正缩负扩）";
            oneD(addEffect(control, "ADBE Slider Control", softenName), "ADBE Slider Control-0001").setValue(0);
            oneD(addEffect(control, "ADBE Slider Control", chokeName), "ADBE Slider Control-0001").setValue(0);
            function connect(parameter, sliderName, lower) {
                if (!parameter.canSetExpression || !parameter.hasMin || !parameter.hasMax) {
                    throw new Error("AE边缘效果不支持预期的数值表达式。");
                }
                var minimum = Math.max(lower, parameter.minValue);
                parameter.setValue(0);
                // Only fixed, generated names enter this expression; no user payload.
                parameter.expression = 'Math.max(' + minimum + ', Math.min(' + parameter.maxValue +
                    ', thisComp.layer("01 整体边缘（效果控件）").effect("' + sliderName + '")(1)));';
                if (parameter.expressionError) throw new Error("AE边缘控制表达式失败：" + parameter.expressionError);
            }
            // Apply to the fully composited matte, not an adjustment layer. Its RGB is
            // discarded by Alpha Track Matte; final color always comes from the original.
            var choke = signedAmount(addEffect(matteLayer, "ADBE Simple Choker", "内部：先收缩或扩展Alpha"));
            connect(choke, chokeName, choke.minValue);
            var blur = oneD(addEffect(matteLayer, "ADBE Gaussian Blur 2", "内部：再柔化Alpha"), "ADBE Gaussian Blur 2-0001");
            connect(blur, softenName, 0);
            return control;
        }
        var names = {rgba: "透明人物", matte: "人物与Alpha修补", paths: "人物矢量路径（近似）"};
        var result = makeComp("MAD · " + names[data.mode] + " · " + data.name);
        if (data.mode === "rgba") {
            layerDefaults(result.layers.add(importSequence(data.rgba, "原始RGBA序列", true)), "透明人物（原始RGBA）");
        } else if (data.mode === "matte") {
            var assets = app.project.items.addFolder("内部素材与修补（自动）");
            assets.parentFolder = folder;
            var original = importSequence(data.source, "完整原画序列", false);
            var rgba = importSequence(data.rgba, "原始Alpha来源（RGBA）", true);
            original.parentFolder = assets;
            rgba.parentFolder = assets;
            var matte = makeComp("局部修补 · " + data.name);
            matte.parentFolder = assets;
            var base = layerDefaults(matte.layers.add(rgba), "原始Alpha底稿（锁定）");
            base.locked = true;
            var restore = repairLayer(matte, "02 补回区域（画添加蒙版）", false, original);
            repairLayer(matte, "01 去除区域（画添加蒙版）", true, original);
            matte.comment = "选补回或去除层，另画闭合添加蒙版；补回直接显示原画。去除优先于补回。此处预览整体边缘处理前的局部结果，整圈柔化/收缩在外层人物合成调整和查看。";
            var fill = layerDefaults(result.layers.add(original), "内部原画（自动关联，请勿修改）");
            var matteLayer = layerDefaults(result.layers.add(matte), "02 局部修补（双击：补回 / 去除）");
            matteLayer.moveBefore(fill);
            if (typeof fill.setTrackMatte === "function") fill.setTrackMatte(matteLayer, TrackMatteType.ALPHA);
            else fill.trackMatteType = TrackMatteType.ALPHA;
            matteLayer.enabled = false;
            matteLayer.label = 9;
            matteLayer.comment = "双击进入局部修补。视频开关关闭是正常的，本层给内部原画提供Alpha；整体边缘请选上方控制层。";
            fill.locked = true;
            fill.shy = true;
            result.hideShyLayers = true;
            var control = edgeControl(result, matteLayer, assets);
            result.comment = "MADSearcher v2：对外使用此人物合成。01整体边缘：效果控件调柔化/收缩；02局部修补：双击后在补回/去除层画添加蒙版。内部素材自动关联，PNG保持原样。";
            for (var selected = 1; selected <= matte.numLayers; selected++) {
                if (!matte.layer(selected).locked) matte.layer(selected).selected = false;
            }
            restore.selected = true;
            for (selected = 1; selected <= result.numLayers; selected++) {
                if (!result.layer(selected).locked) result.layer(selected).selected = false;
            }
            control.selected = true;
        } else {
            var layer = layerDefaults(result.layers.add(importSequence(data.source, "完整原画序列", false)), "人物（可编辑矢量近似）");
            var times = [];
            for (var f = 0; f < data.count; f++) times.push(f / data.fps);
            for (var depth = 0; depth < data.slots.length; depth++) {
                for (var slot = 0; slot < data.slots[depth]; slot++) {
                    var pathMask = layer.property("ADBE Mask Parade").addProperty("ADBE Mask Atom");
                    pathMask.name = "MAD d" + depth + " p" + slot;
                    pathMask.maskMode = depth % 2 ? MaskMode.SUBTRACT : MaskMode.ADD;
                    pathMask.rotoBezier = false;
                    var shapes = [];
                    for (var frame = 0; frame < data.count; frame++) {
                        var group = data.frames[frame][depth];
                        var points = group && group[slot] ? group[slot] : [[-4,-4],[-3,-4],[-3,-3]];
                        shapes.push(polygon(points));
                    }
                    var path = pathMask.property("ADBE Mask Shape");
                    path.setValuesAtTimes(times, shapes);
                    for (var key = 1; key <= path.numKeys; key++) {
                        path.setInterpolationTypeAtKey(key, KeyframeInterpolationType.HOLD, KeyframeInterpolationType.HOLD);
                    }
                }
            }
        }
        if (target instanceof CompItem) {
            var start = Math.max(0, target.time);
            if (target.duration < start + duration) target.duration = start + duration;
            var placed = layerDefaults(target.layers.add(result), result.name);
            placed.startTime = start;
            placed.inPoint = start;
            placed.outPoint = start + duration;
            target.openInViewer();
        } else result.openInViewer();
    } catch (error) {
        alert("MADSearcher: " + error.toString() + "\nUndo once to remove this partial import. Your project has not been saved.");
    } finally { app.endUndoGroup(); }
})();
